folder_path = 'C:/Users/andre/Desktop/Binance_CSV/'

URL = [
        'https://www.cryptodatadownload.com/cdd/Binance_BTCUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_ETHUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_LTCUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_NEOUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_BNBUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_XRPUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_LINKUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_EOSUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_TRXUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_ETCUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_XLMUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_ZECUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_ADAUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_QTUMUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_DASHUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_XMRUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_BATUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_BTTUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_USDCUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_TUSDUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_MATICUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_PAXUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_CELRUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_ONEUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_DOTUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_UNIUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_ICPUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_SOLUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_VETUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_FILUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_AAVEUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_DAIUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_MKRUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_ICXUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_CVCUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_SCUSDT_1h.csv',
        'https://www.cryptodatadownload.com/cdd/Binance_LRCUSDT_1h.csv',
         ]

start_name_URL = 47
end_name_URL = '_'
